name: Android App Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 24
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew assembleRelease

      - name: Upload release apk
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app-release
          path: app/build/outputs/apk/release